=== d1vij/d1vij.github.io/public/schemas/project.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "title": {
            "type": "string",
            "minLength": 1
        },
        "images": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string",
                        "minLength": 1
                    },
                    "url": {
                        "type": "string",
                        "pattern": "^\\/(?:[a-zA-Z0-9_-]+\\/)*[a-zA-Z0-9_-]+\\.(png|jpeg|jpg|webp)$"
                    }
                },
                "required": ["title", "url"],
                "additionalProperties": false
            }
        },
        "links": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "url": {
                        "type": "string",
                        "format": "uri"
                    },
                    "for": {
                        "type": "string",
                        "minLength": 1
                    }
                },
                "required": ["url", "for"],
                "additionalProperties": false
            }
        },
        "stack": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "section": {
                        "type": "string",
                        "minLength": 1
                    },
                    "used": {
                        "type": "array",
                        "items": {
                            "anyOf": [
                                {
                                    "type": "string",
                                    "pattern": "^\\*.*"
                                },
                                {
                                    "type": "string",
                                    "enum": [
                                        "React",
                                        "TailwindCSS",
                                        "TypeScript",
                                        "Express",
                                        "HTML",
                                        "SCSS",
                                        "Python",
                                        "FastApi",
                                        "Pandas",
                                        "Numpy",
                                        "Jupyter",
                                        "Docker",
                                        "MongoDB"
                                    ]
                                }
                            ]
                        }
                    }
                },
                "required": ["section", "used"],
                "additionalProperties": false
            }
        },
        "text": {
            "type": "array",
            "items": {
                "type": "string",
                "minLength": 1
            }
        }
    },
    "required": ["title", "images", "links", "stack", "text"],
    "additionalProperties": false
}

=== d1vij/d1vij.github.io/public/projects/spotify-data-analysis.json
{
    "$schema": "../schemas/project.schema.json",
    "title": "Spotify Data Analysis",
    "images": [
        {
            "title": "Dummy 1",
            "url": "/images/dummy-1.jpeg"
        },
        {
            "title": "Dummy 2",
            "url": "/images/dummy-4.jpeg"
        },
        {
            "title": "Dummy 3",
            "url": "/images/dummy-4.jpeg"
        },
        {
            "title": "Dummy 4",
            "url": "/images/dummy-5.jpeg"
        },
        {
            "title": "Dummy 5",
            "url": "/images/dummy-5.jpeg"
        }
    ],
    "links": [
        {
            "for": "github",
            "url": "http://github.com/d1vij/spotify-data-analysis"
        },
        {
            "for": "website",
            "url": "https://d1vij.github.io/spotify-data-analysis/"
        }
    ],
    "stack": [
        {
            "section": "Analysis",
            "used": ["Python", "Pandas", "Numpy", "*Matplotlib", "*Seaborn"]
        },
        {
            "section": "Runtime",
            "used": ["Jupyter"]
        }
    ],
    "text": [
        "LLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmorem ipsm",
        "Lorem ipsm",
        "Lorem iLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmpsm",
        "Lorem ipsm",
        "Lorem ipsm",
        "Lorem ipLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmLorem ipsmsm",
        "Lorem ipsm"
    ]
}
